kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim1
  namespace: docker-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: task-pv-volume1